# Generated by Django 5.0.3 on 2026-07-31 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('request_id', models.UUIDField(db_index=True)),
                ('tool_name', models.CharField(blank=True, default='', max_length=64)),
                ('params_safe', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant query log',
                'verbose_name_plural': 'Assistant query logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schema_name', '-created_at'], name='appassistan_schema__59c196_idx'), models.Index(fields=['tool_name', '-created_at'], name='appassistan_tool_na_f3b436_idx')],
            },
        ),
    ]
