# Generated by Django 5.0.3 on 2026-08-01 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appassistant', '0001_initial_assistant_query_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantquerylog',
            name='clarification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistantquerylog',
            name='intent',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('state_schema_version', models.CharField(default='1', max_length=8)),
                ('turn_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant conversation',
                'verbose_name_plural': 'Assistant conversations',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.AddField(
            model_name='assistantquerylog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='appassistant.assistantconversation'),
        ),
        migrations.AddIndex(
            model_name='assistantquerylog',
            index=models.Index(fields=['conversation', '-created_at'], name='appassistan_convers_7b9421_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', '-last_activity_at'], name='appassistan_user_id_79e397_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['is_active', 'last_activity_at'], name='appassistan_is_acti_e1a921_idx'),
        ),
    ]
