# Generated by Django 5.0.3 on 2025-12-10 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appschedule', '0001_initial'),
        ('apptransactions', '0002_initial'),
        ('crewsapp', '0001_initial'),
        ('ctrctsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='events', to='ctrctsapp.builder'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewsapp.crew', verbose_name='Crew'),
        ),
        migrations.AddField(
            model_name='event',
            name='house_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='events', to='ctrctsapp.housemodel'),
        ),
        migrations.AddField(
            model_name='event',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='events', to='ctrctsapp.job'),
        ),
        migrations.AddField(
            model_name='event',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='apptransactions.workaccount'),
        ),
        migrations.AddField(
            model_name='eventchatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventchatmessage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='appschedule.event'),
        ),
        migrations.AddField(
            model_name='eventchatreadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='appschedule.eventchatmessage'),
        ),
        migrations.AddField(
            model_name='eventchatreadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='absence_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appschedule.absencereason'),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='drafts', to='ctrctsapp.builder'),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='drafts', to='crewsapp.crew'),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appschedule.event', verbose_name='events_draft'),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='house_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='drafts', to='ctrctsapp.housemodel'),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='drafts', to='ctrctsapp.job'),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_drafts', to='apptransactions.workaccount'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appschedule.event'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventnote',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='appschedule.event', verbose_name='event_note'),
        ),
        migrations.AddField(
            model_name='eventnote',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'end_dt'], name='appschedule_date_e53183_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['work_account', 'is_absence'], name='appschedule_work_ac_f8021e_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('crew', 'date', 'title'), name='uniq_event_crew_date_title'),
        ),
        migrations.AlterUniqueTogether(
            name='eventchatreadstatus',
            unique_together={('user', 'message')},
        ),
        migrations.AddIndex(
            model_name='eventdraft',
            index=models.Index(fields=['date', 'end_dt'], name='appschedule_date_e9ad61_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdraft',
            index=models.Index(fields=['work_account', 'is_absence'], name='appschedule_work_ac_cac00a_idx'),
        ),
    ]
