# Generated by Django 5.0.3 on 2025-12-25 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschedule', '0002_initial'),
        ('apptransactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnote',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_notes', to='apptransactions.workaccount', verbose_name='work_account_note'),
        ),
        migrations.AlterField(
            model_name='eventnote',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='appschedule.event', verbose_name='event_note'),
        ),
        migrations.AddConstraint(
            model_name='eventnote',
            constraint=models.UniqueConstraint(condition=models.Q(('work_account__isnull', False)), fields=('work_account',), name='unique_work_account_note'),
        ),
    ]
