# Generated by Django 5.0.3 on 2025-12-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschedule', '0003_eventnote_work_account_alter_eventnote_event_and_more'),
        ('apptransactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchatmessage',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_account_chat_messages', to='apptransactions.workaccount'),
        ),
        migrations.AlterField(
            model_name='eventchatmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='appschedule.event'),
        ),
        migrations.AddConstraint(
            model_name='eventchatmessage',
            constraint=models.CheckConstraint(check=models.Q(('event__isnull', False), ('work_account__isnull', False), _connector='OR'), name='event_chat_message_requires_event_or_work_account'),
        ),
    ]
