# Generated by Django 5.0.3 on 2025-12-25 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschedule', '0004_eventchatmessage_work_account_and_more'),
        ('apptransactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apptransactions.workaccount'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appschedule.event'),
        ),
        migrations.AddConstraint(
            model_name='eventimage',
            constraint=models.CheckConstraint(check=models.Q(('event__isnull', False), ('work_account__isnull', False), _connector='OR'), name='event_image_requires_event_or_work_account'),
        ),
    ]
