# Generated by Django 5.0.3 on 2026-09-13 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschedule', '0005_eventimage_work_account_alter_eventimage_event_and_more'),
        ('apptransactions', '0007_protect_work_account_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchatmessage',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_account_chat_messages', to='apptransactions.workaccount'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='apptransactions.workaccount'),
        ),
    ]
