# Generated by Django 5.0.3 on 2026-09-13 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschedule', '0006_protect_work_account_relations'),
        ('apptransactions', '0007_protect_work_account_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='apptransactions.workaccount'),
        ),
        migrations.AlterField(
            model_name='eventchatmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to='appschedule.event'),
        ),
        migrations.AlterField(
            model_name='eventdraft',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_drafts', to='apptransactions.workaccount'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='appschedule.event'),
        ),
    ]
