# Generated by Django 5.0.3 on 2025-12-10 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctrctsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plate Number')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Crew Name')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('permission_create_event', models.BooleanField(default=False, verbose_name='Can Create/Update Schedule?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crewsapp.category', verbose_name='Category')),
                ('jobs', models.ManyToManyField(blank=True, related_name='crews', to='ctrctsapp.job', verbose_name='Assigned Jobs')),
                ('members', models.ManyToManyField(blank=True, related_name='crews', to=settings.AUTH_USER_MODEL, verbose_name='Crew Members')),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crews',
            },
        ),
        migrations.CreateModel(
            name='TruckAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(verbose_name='Assigned At')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Unassigned At')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewsapp.crew', verbose_name='Assigned Crew')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewsapp.truck', verbose_name='Assigned Truck')),
            ],
        ),
    ]
