# Generated by Django 5.0.3 on 2025-11-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        # Usar RunSQL para agregar client_type solo si no existe
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema = 'public' 
                        AND table_name = 'tenants_tenant' 
                        AND column_name = 'client_type'
                    ) THEN
                        ALTER TABLE public.tenants_tenant 
                        ADD COLUMN client_type VARCHAR(50) DEFAULT 'general';
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE public.tenants_tenant 
                DROP COLUMN IF EXISTS client_type;
            """,
        ),
        # Usar SeparateDatabaseAndState para agregar el campo al modelo sin tocar la BD
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No hacer nada en la BD, ya lo hicimos arriba
            ],
            state_operations=[
                migrations.AddField(
                    model_name='tenant',
                    name='client_type',
                    field=models.CharField(choices=[('electric', 'Electric'), ('air_conditioning', 'Air Conditioning'), ('solar', 'Solar'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('general', 'General')], default='general', max_length=50, verbose_name='Tipo de Cliente'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Logo del Cliente'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Tenant ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='En período de prueba'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Pagado hasta'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(blank=True, db_index=True, max_length=63, unique=True, verbose_name='Schema Name'),
        ),
    ]
