# Generated by Django 5.0.3 on 2025-11-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options_tenant_client_type_tenant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admin_temp_password',
            field=models.CharField(blank=True, help_text='Contraseña temporal del admin inicial (solo desarrollo)', max_length=128, null=True, verbose_name='Contraseña Temporal Admin'),
        ),
    ]
