# Generated by Django 5.0.3 on 2025-12-10 05:56

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appinventory', '0001_initial'),
        ('apptransactions', '0001_initial'),
        ('ctrctsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ctrctsapp.builder'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentline',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appinventory.productbrand'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='apptransactions.document'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appinventory.pricetype'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appinventory.product'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appinventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appinventory.warehouse'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptransactions.documenttype'),
        ),
        migrations.AddField(
            model_name='party',
            name='default_price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinventory.pricetype'),
        ),
        migrations.AddField(
            model_name='party',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apptransactions.partycategory'),
        ),
        migrations.AddField(
            model_name='party',
            name='types',
            field=models.ManyToManyField(to='apptransactions.partytype'),
        ),
        migrations.AddField(
            model_name='transactionfavorite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workaccount',
            name='builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_accounts', to='ctrctsapp.builder'),
        ),
        migrations.AddField(
            model_name='workaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workaccount',
            name='default_price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appinventory.pricetype'),
        ),
        migrations.AddField(
            model_name='workaccount',
            name='house_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ctrctsapp.housemodel'),
        ),
        migrations.AddField(
            model_name='workaccount',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ctrctsapp.job'),
        ),
        migrations.AddField(
            model_name='document',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apptransactions.workaccount'),
        ),
        migrations.AddIndex(
            model_name='transactionfavorite',
            index=models.Index(fields=['created_by', 'is_active'], name='apptransact_created_5c5bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionfavorite',
            index=models.Index(fields=['name'], name='apptransact_name_5d9ca8_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionfavorite',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name', 'created_by'), name='unique_favorite_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='workaccount',
            index=models.Index(django.db.models.functions.text.Lower('title'), name='idx_workaccount_title_ci'),
        ),
        migrations.AddConstraint(
            model_name='workaccount',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), condition=models.Q(('is_active', True)), name='uniq_workaccount_title_ci_active'),
        ),
        migrations.AddConstraint(
            model_name='workaccount',
            constraint=models.UniqueConstraint(models.F('builder'), models.F('job'), django.db.models.functions.text.Lower('lot'), condition=models.Q(('is_active', True), models.Q(('lot', ''), _negated=True)), name='uniq_workaccount_builder_job_lot_ci_active'),
        ),
        migrations.AddConstraint(
            model_name='workaccount',
            constraint=models.UniqueConstraint(models.F('builder'), models.F('job'), django.db.models.functions.text.Lower('address'), condition=models.Q(('is_active', True), ('lot', ''), models.Q(('address', ''), _negated=True)), name='uniq_workaccount_builder_job_address_ci_active_when_no_lot'),
        ),
    ]
