# Generated by Django 5.0.3 on 2026-03-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='creates_serialized_items',
            field=models.BooleanField(default=False, help_text='Document type that creates/registers serialized items; opens asset tag assignment modal when document has serialized items.'),
        ),
    ]
