# Generated by Django 5.0.3 on 2026-04-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransactions', '0003_add_document_type_creates_serialized_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='margin_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Snapshot: markup or margin % used when the line was saved.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='documentline',
            name='pricing_rule',
            field=models.CharField(blank=True, choices=[('MARKUP', 'Markup %'), ('MARGIN', 'Margin %'), ('MANUAL', 'Manual unit price')], max_length=10, null=True),
        ),
    ]
