# Generated by Django 5.0.3 on 2026-09-13 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransactions', '0006_documenttype_assistant_intentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='apptransactions.workaccount'),
        ),
    ]
