# Generated by Django 5.0.3 on 2026-09-26 00:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

MR_STATUSES = (
    ('requested', 'Requested', 1, True, False),
    ('approved', 'Approved', 2, False, False),
    ('preparing', 'Preparing', 3, False, False),
    ('delivered', 'Delivered', 4, False, False),
    ('closed', 'Closed', 5, False, True),
)


def seed_material_request(apps, schema_editor):
    DocumentType = apps.get_model('apptransactions', 'DocumentType')
    DocumentStatus = apps.get_model('apptransactions', 'DocumentStatus')
    # Algunos schemas tienen la secuencia de id detrás del máximo real.
    schema_editor.execute(
        "SELECT setval(pg_get_serial_sequence('apptransactions_documenttype', 'id'), "
        "COALESCE((SELECT MAX(id) FROM apptransactions_documenttype), 1))"
    )
    document_type, _created = DocumentType.objects.get_or_create(
        type_code='MR',
        defaults={
            'description': 'Material Request',
            'affects_physical': False,
            'affects_logical': False,
            'affects_accounting': False,
            'is_taxable': False,
            'is_purchase': False,
            'is_sales': False,
            'warehouse_required': False,
            'is_operational': True,
            'prices_required': False,
            'allow_negative_sales': False,
            'creates_serialized_items': False,
            'stock_movement': 0,
            'is_active': True,
        },
    )
    document_type.prices_required = False
    document_type.is_operational = True
    document_type.is_sales = False
    document_type.is_purchase = False
    document_type.warehouse_required = False
    document_type.stock_movement = 0
    document_type.save()
    for code, name, sequence, is_initial, is_terminal in MR_STATUSES:
        DocumentStatus.objects.get_or_create(
            document_type=document_type,
            code=code,
            defaults={
                'name': name,
                'sequence': sequence,
                'is_initial': is_initial,
                'is_terminal': is_terminal,
                'is_active': True,
            },
        )


def unseed_material_request(apps, schema_editor):
    DocumentType = apps.get_model('apptransactions', 'DocumentType')
    DocumentType.objects.filter(type_code='MR').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('appschedule', '0008_eventnote_remove_unique_work_account'),
        ('apptransactions', '0007_protect_work_account_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='appschedule.event'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='prices_required',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('picking', 'Picking'), ('purchase_order', 'Purchase order')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_links_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_links', to='apptransactions.document')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_links', to='apptransactions.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='apptransactions.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('sequence', models.PositiveIntegerField()),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='apptransactions.documenttype')),
            ],
            options={
                'ordering': ['document_type', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_tracking_changes', to=settings.AUTH_USER_MODEL)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_documents', to='apptransactions.documentstatus')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='apptransactions.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_tracking_history', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='apptransactions.document')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_from', to='apptransactions.documentstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_to', to='apptransactions.documentstatus')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentlink',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation'), name='uniq_document_link_source_target_relation'),
        ),
        migrations.AddConstraint(
            model_name='documentstatus',
            constraint=models.UniqueConstraint(fields=('document_type', 'code'), name='uniq_document_status_type_code'),
        ),
        migrations.AddConstraint(
            model_name='documentstatus',
            constraint=models.UniqueConstraint(fields=('document_type', 'sequence'), name='uniq_document_status_type_sequence'),
        ),
        migrations.RunPython(seed_material_request, unseed_material_request),
    ]
