# Generated by Django 5.0.3 on 2026-09-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransactions', '0008_material_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apptransactions.documenttype'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sequence', to='apptransactions.documenttype'),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='apptransactions.documenttype'),
        ),
    ]
