# Generated by Django 5.0.3 on 2025-12-10 05:56

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appinventory', '0001_initial'),
        ('appschedule', '0001_initial'),
        ('apptransactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('trim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Trim Price SqFt')),
                ('rough_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rough Price SqFt')),
                ('travel_price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Travel Amount')),
                ('rfc', models.CharField(blank=True, max_length=50, verbose_name='RFC')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('floor_office', models.CharField(blank=True, max_length=100, verbose_name='Floor/Office')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('customer_rank', models.PositiveIntegerField(default=0, verbose_name='Customer Rank')),
                ('supplier_rank', models.PositiveIntegerField(default=0, verbose_name='Supplier Rank')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apptransactions.partycategory', verbose_name='Category')),
                ('default_price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinventory.pricetype', verbose_name='Default Price Type')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builders', to='apptransactions.party')),
                ('types', models.ManyToManyField(blank=True, to='apptransactions.partytype', verbose_name='Party Types')),
            ],
            options={
                'verbose_name': 'Builder',
                'verbose_name_plural': 'Builders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('builder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ctrctsapp.builder')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities (Job)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('jobs', models.ManyToManyField(related_name='house_models', to='ctrctsapp.job')),
            ],
            options={
                'verbose_name': 'House Model',
                'verbose_name_plural': 'House Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Rough', 'Rough'), ('Trim', 'Trim')], max_length=5)),
                ('doc_type', models.CharField(choices=[('Contract', 'Contract'), ('Bid', 'Bid')], default='Contract', max_length=10)),
                ('lot', models.CharField(max_length=10, null=True, verbose_name='Lot')),
                ('sqft', models.IntegerField(verbose_name='SqFt')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('job_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Job Price')),
                ('travel_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Travel Price')),
                ('total_options', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Options')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total')),
                ('comment', models.TextField(default='Required to finish at 100%', null=True, verbose_name='Comment')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='contract', verbose_name='File')),
                ('needs_reprint', models.BooleanField(default=False)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctrctsapp.builder', verbose_name='Builder')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appschedule.event', verbose_name='Schedule')),
                ('work_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='apptransactions.workaccount', verbose_name='Work Account')),
                ('house_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctrctsapp.housemodel', verbose_name='House Model')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctrctsapp.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='WorkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('trim', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Trim')),
                ('rough', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rough')),
                ('unit_price', models.CharField(max_length=255, verbose_name='Unit Price Type')),
                ('builders', models.ManyToManyField(related_name='work_prices', to='ctrctsapp.builder', verbose_name='Builders')),
            ],
            options={
                'verbose_name': 'Work Price',
                'verbose_name_plural': 'Work Prices',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdname', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cdtrim', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Trim Qty')),
                ('cdtrim_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Trim')),
                ('cdrough', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rough')),
                ('cdrough_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rough Qty')),
                ('cdunit_price', models.CharField(max_length=255, verbose_name='Unit Price Type')),
                ('contract_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_details', to='ctrctsapp.contract', verbose_name='Work Price Details')),
                ('cdwork_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priceDetails', to='ctrctsapp.workprice', verbose_name='Price Details')),
            ],
            options={
                'verbose_name': 'Contract Detail',
                'verbose_name_plural': 'Contract Details',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='builder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_builder_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='builder',
            constraint=models.UniqueConstraint(models.F('rfc'), condition=models.Q(('rfc__isnull', False), ('rfc__gt', '')), name='uniq_builder_rfc'),
        ),
    ]
