# Generated by Django 5.0.3 on 2026-09-13 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransactions', '0007_protect_work_account_relations'),
        ('ctrctsapp', '0002_contract_lot_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='work_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='apptransactions.workaccount', verbose_name='Work Account'),
        ),
    ]
