# Generated by Django 5.0.3 on 2026-09-13 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschedule', '0007_protect_event_relations'),
        ('ctrctsapp', '0003_protect_work_account_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='appschedule.event', verbose_name='Schedule'),
        ),
    ]
