# Generated by Django 5.0.3 on 2026-06-04 00:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('document_line', 'Document line'), ('document', 'Document'), ('builder', 'Builder')], max_length=32)),
                ('source_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], default='upsert', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Index outbox entry',
                'verbose_name_plural': 'Index outbox entries',
                'ordering': ['created_at'],
                'indexes': [models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['processed_at', 'created_at'], name='search_outbox_pending')],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('document_line', 'Document line'), ('document', 'Document'), ('builder', 'Builder')], max_length=32)),
                ('source_id', models.PositiveBigIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=64)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search index entry',
                'verbose_name_plural': 'Search index entries',
                'ordering': ['-updated_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='searchindex_search_vector_gin'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='searchindex_metadata_gin'), models.Index(fields=['source_type', 'indexed_at'], name='searchindex_type_indexed'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='searchindex_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.AddConstraint(
            model_name='searchindex',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='uniq_searchindex_source'),
        ),
    ]
