# Generated by Django 5.0.3 on 2026-01-23 01:59

import appinventory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=appinventory.models.product_image_upload_to)),
                ('is_primary', models.BooleanField(default=False, help_text='Indica si esta es la imagen principal para esta marca del producto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Descripción opcional de la imagen', max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='appinventory.productbrand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appinventory.product')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', '-uploaded_at'],
                'indexes': [models.Index(fields=['product', 'brand'], name='appinventor_product_b8f796_idx'), models.Index(fields=['product', 'brand', 'is_primary'], name='appinventor_product_41d72b_idx')],
            },
        ),
    ]
