# Generated by Django 5.0.3 on 2026-01-24 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_data(apps, schema_editor):
    Product = apps.get_model('appinventory', 'Product')
    ProductBrandAssignment = apps.get_model('appinventory', 'ProductBrandAssignment')
    ProductImage = apps.get_model('appinventory', 'ProductImage')
    
    from django.db import connection
    with connection.cursor() as cursor:
        # 1. Copiar datos de marcas de productos a ProductBrandAssignment
        # El nombre de la tabla automática es appinventory_product_brands
        cursor.execute("SELECT count(*) FROM information_schema.tables WHERE table_name = 'appinventory_product_brands'")
        if cursor.fetchone()[0] > 0:
            cursor.execute("SELECT product_id, productbrand_id FROM appinventory_product_brands")
            for product_id, brand_id in cursor.fetchall():
                ProductBrandAssignment.objects.get_or_create(
                    product_id=product_id,
                    brand_id=brand_id
                )
        
        # 2. Vincular imágenes existentes a las nuevas asignaciones
        # Como aún no hemos eliminado el campo 'brand_id' de la base de datos (solo del estado de Django),
        # podemos consultarlo directamente.
        cursor.execute("SELECT count(*) FROM information_schema.columns WHERE table_name = 'appinventory_productimage' AND column_name = 'brand_id'")
        if cursor.fetchone()[0] > 0:
            cursor.execute("SELECT id, product_id, brand_id FROM appinventory_productimage")
            for img_id, prod_id, brand_id in cursor.fetchall():
                assignment = ProductBrandAssignment.objects.filter(product_id=prod_id, brand_id=brand_id).first()
                if assignment:
                    ProductImage.objects.filter(id=img_id).update(assignment=assignment)

class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0002_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Crear el modelo intermedio
        migrations.CreateModel(
            name='ProductBrandAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='appinventory.productbrand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_assignments', to='appinventory.product')),
            ],
            options={
                'verbose_name': 'Product Brand Assignment',
                'verbose_name_plural': 'Product Brand Assignments',
                'unique_together': {('product', 'brand')},
            },
        ),
        
        # 2. Preparar ProductImage para la nueva relación
        migrations.AddField(
            model_name='productimage',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appinventory.productbrandassignment'),
        ),
        
        # 3. Alterar temporalmente product para que sea nullable (si no lo era)
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appinventory.product'),
        ),

        # 4. Migrar los datos
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),

        # 5. Limpiar campos antiguos del estado y base de datos
        migrations.RemoveIndex(
            model_name='productimage',
            name='appinventor_product_b8f796_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='appinventor_product_41d72b_idx',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='brand',
        ),
        
        # 6. Cambiar brands en Product (Eliminar y volver a añadir)
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(related_name='products', through='appinventory.ProductBrandAssignment', to='appinventory.productbrand'),
        ),

        # 7. Añadir nuevos índices
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['assignment'], name='appinventor_assignm_291eff_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['assignment', 'is_primary'], name='appinventor_assignm_e20459_idx'),
        ),
    ]
