# Generated by Django 5.0.3 on 2026-01-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0003_productbrandassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appinventory.productbrandassignment'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appinventory.product'),
        ),
    ]
