# Generated by Django 5.0.3 on 2026-02-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0004_alter_productimage_assignment_and_more'),
        ('appinventory', '0006_warehouse_truck'),
    ]

    operations = [
    ]
