# Generated by Django 5.0.3 on 2026-02-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0007_inventory_transfer_header_and_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida'), (0, 'Ajuste/Transfer')]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appinventory.productbrandassignment'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appinventory.product'),
        ),
        migrations.AlterField(
            model_name='serializeditem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Lost', 'Lost'), ('Retired', 'Retired')], default='Active', max_length=20),
        ),
    ]
