# Generated by Django 5.0.3 on 2026-02-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0007_merge_20260219_0348'),
        ('appinventory', '0008_alter_inventorymovement_movement_type_and_more'),
    ]

    operations = [
    ]
