# Generated by Django 5.0.3 on 2026-04-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0009_merge_20260222_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='margin_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Markup or margin % (0–100) when pricing_method is MARKUP or MARGIN.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='pricing_method',
            field=models.CharField(choices=[('NONE', 'No auto pricing from cost'), ('MARKUP', 'Markup % on cost'), ('MARGIN', 'Margin % on cost')], default='NONE', help_text='How sale price is derived from purchase cost on transaction lines.', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida'), (0, 'Ajuste/Transfer (Neutral)')]),
        ),
        migrations.AlterField(
            model_name='serializeditem',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='Unique serial number or QR identifier', max_length=100, null=True, unique=True, verbose_name='Serial Number'),
        ),
    ]
