# Generated by Django 5.0.3 on 2025-12-10 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cliente')),
                ('schema_name', models.CharField(blank=True, db_index=True, max_length=63, unique=True, verbose_name='Schema Name')),
                ('tenant_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Tenant ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('client_type', models.CharField(choices=[('electric', 'Electric'), ('air_conditioning', 'Air Conditioning'), ('solar', 'Solar'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('general', 'General')], default='general', max_length=50, verbose_name='Tipo de Cliente')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Logo del Cliente')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('preferences', models.JSONField(blank=True, default=list, help_text='Lista de módulos activados para este tenant', verbose_name='Módulos Activados')),
                ('monthly_operations', models.CharField(blank=True, choices=[('0-10', '0–10 homes per month'), ('11-25', '11–25 homes per month'), ('26-50', '26–50 homes per month'), ('51-100', '51–100 homes per month'), ('100+', '100+ homes per month')], help_text='How many projects or homes the company handles each month', max_length=10, null=True, verbose_name='Monthly Operations Volume')),
                ('crew_count', models.IntegerField(blank=True, help_text='How many active crews the company manages', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Active Crews')),
                ('recommended_plan', models.CharField(blank=True, choices=[('Starter', 'Starter'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], help_text='Recommended plan based on crew count', max_length=20, null=True, verbose_name='Recommended Plan')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Pagado hasta')),
                ('on_trial', models.BooleanField(default=True, verbose_name='En período de prueba')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('admin_temp_password', models.CharField(blank=True, help_text='Contraseña temporal del admin inicial (solo desarrollo)', max_length=128, null=True, verbose_name='Contraseña Temporal Admin')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
