# Generated by Django 5.0.3 on 2026-01-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='seed_inventory_done',
            field=models.BooleanField(default=False, help_text='Indica si los datos maestros de inventario han sido importados para este tenant', verbose_name='Datos Maestros de Inventario Importados'),
        ),
    ]
