# Generated by Django 5.0.3 on 2026-01-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_seed_inventory_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='admin_temp_password',
        ),
    ]
