# Generated by Django 5.0.3 on 2026-06-03 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_trial_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='client_type',
            field=models.CharField(choices=[('electric', 'Electric'), ('air_conditioning', 'Air Conditioning'), ('solar', 'Solar'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('general', 'General')], default='general', max_length=50, verbose_name='Client type'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Client logo'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='On trial'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Paid until'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial end'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial start'),
        ),
        migrations.CreateModel(
            name='OnboardingPendingRegistration',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('company_name', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='onboarding_pending/')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pending onboarding registration',
                'verbose_name_plural': 'Pending onboarding registrations',
                'indexes': [models.Index(fields=['email', 'consumed_at'], name='tenants_onb_email_33f574_idx')],
            },
        ),
    ]
